# Review of Matrix Basics
The goal of this python code is to familiarize oneself with the basics
of vectors, matrix transposes, dot products, and multiplication.

In [2]:
### ATOC5860 - linear_algebra_basics.ipynb
## coded by Dr. Eleanor Middlemas (postdoc ATOC/CIRES University of Colorado, now working at Jupiter)
## Last updated February 9, 2022

import numpy as np
%matplotlib inline

In [7]:
# Vectors are arrays that have a singleton dimension.
v = np.zeros((3,1))
print("This is a vector of zeros.")
print(v)
print("Its dimension sizes are ",np.shape(v))
print("")

# Transposing vectors:
print("This vector transposed looks like: ")
print() # put transposed vector here using np. function
print("Its new size is ",np.shape(np.transpose(v)))
print("Its new size is ",np.shape(v.T))

This is a vector of zeros.
[[0.]
 [0.]
 [0.]]
Its dimension sizes are  (3, 1)

This vector transposed looks like: 

Its new size is  (1, 3)
Its new size is  (1, 3)


In [8]:
# Matrices *can* be (though not always) a compilation of vectors.
v = [1,2,3]
v2 = [2,4,6]

# put these two vectors into V. the ".T" makes them column vectors.
V = np.matrix([v,v2]).T
print(V)
print("The above matrix is comprise of two column vectors.")
print("Its size is ",np.shape(V))
print("")

# Transposing a matrix involves transposing each of its vectors.
Vt =  V.T# numpy arrays may be tranposed by appending a ".T"
print("V transposed looks like: ")
print(Vt)
print("Its new sizes are: ",np.shape(Vt))

[[1 2]
 [2 4]
 [3 6]]
The above matrix is comprise of two column vectors.
Its size is  (3, 2)

V transposed looks like: 
[[1 2 3]
 [2 4 6]]
Its new sizes are:  (2, 3)


In [9]:
# The dot product is simply the sum of the product of each corresponding
# position of vectors. The dot product between two vectors also yields
# the covariance.

# recall that:
v = np.array([1,2,3])
v2 = np.array([2,4,6])
# please write out the actual calculation of computing the dot product 
# of v and v2 above (i.e., how you would calculate it by hand).
dot1 = 1*2+2*4+3*6
print(dot1)

print(v.shape)
print(v2.shape)
# Use the numpy function "dot":
dot2 = np.dot(v,v2)
print("Dot product calculated using numpy: ",dot2)

# What about the dot product of these two vectors?
v3 = [5,15,20]
x = [1,2]

28
(3,)
(3,)
Dot product calculated using numpy:  28


In [10]:
# Matrix multiplication is simply the dot products between the rows
# in the first matrix and the columns in the second matrix.
# Before beginning to multiply, you must make sure your matrices/vectors are conformable.

A = v2*V  
print("v2: ",v2)
print("V: ",V)
print("v2*V: ",A)

#B = V*v

C = np.matrix([v,v2,v3])
print("New matrix C has a shape of size ",np.shape(C))
print("What will the size of CxV (size ",np.shape(V),") look like?")

D = C@V  ## @ is matrix multiplication -- * will default to scalar multiplication
print("Shape of CxV is ",np.shape(D))

v2:  [2 4 6]
V:  [[1 2]
 [2 4]
 [3 6]]
v2*V:  [[28 56]]
New matrix C has a shape of size  (3, 3)
What will the size of CxV (size  (3, 2) ) look like?
Shape of CxV is  (3, 2)
